import io
import json
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import simpleSplit


def generate_pdf_report(candidate_name, role, difficulty, interview_type, report):
    """
    Generates a professional PDF interview report.
    Returns PDF as BYTES (perfect for Streamlit download_button).
    """

    # ---------------- SAFE JSON ----------------
    if report is None:
        report = {}

    if isinstance(report, str):
        try:
            report = json.loads(report)
        except:
            report = {}

    if not isinstance(report, dict):
        report = {}

    # ---------------- GET REPORT DATA ----------------
    overall_score = report.get("overall_score", 0)
    verdict = report.get("verdict", "UNKNOWN")
    summary_feedback = report.get("summary_feedback", "No summary feedback provided.")
    improvement_plan = report.get("improvement_plan", "No improvement plan provided.")
    question_wise = report.get("question_wise", [])

    # ---------------- CREATE PDF BUFFER ----------------
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)

    width, height = letter
    y = height - 60

    # ---------------- HELPER FUNCTION ----------------
    def add_text_block(title, text, y_pos, font_size=11, max_width=85):
        """
        Adds wrapped text block safely to PDF.
        Returns updated y position.
        """
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y_pos, title)
        y_pos -= 20

        c.setFont("Helvetica", font_size)
        lines = simpleSplit(str(text), "Helvetica", font_size, max_width * 6)

        for line in lines:
            if y_pos < 60:
                c.showPage()
                y_pos = height - 60
                c.setFont("Helvetica", font_size)

            c.drawString(60, y_pos, line)
            y_pos -= 15

        return y_pos - 10

    # ---------------- HEADER ----------------
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, y, "AI Interview Report")
    y -= 40

    c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Candidate Name: {candidate_name}")
    y -= 20
    c.drawString(50, y, f"Role: {role}")
    y -= 20
    c.drawString(50, y, f"Difficulty: {difficulty}")
    y -= 20
    c.drawString(50, y, f"Interview Type: {interview_type}")
    y -= 20
    c.drawString(50, y, f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    y -= 35

    # ---------------- SCORE SECTION ----------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, f"Overall Score: {overall_score}/10")
    y -= 25
    c.drawString(50, y, f"Verdict: {verdict}")
    y -= 40

    # ---------------- SUMMARY ----------------
    y = add_text_block("Summary Feedback:", summary_feedback, y)

    # ---------------- IMPROVEMENT PLAN ----------------
    y = add_text_block("Improvement Plan:", improvement_plan, y)

    # ---------------- QUESTION WISE ----------------
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Question-wise Evaluation")
    y -= 25

    if isinstance(question_wise, list) and len(question_wise) > 0:

        for i, item in enumerate(question_wise, start=1):

            if not isinstance(item, dict):
                continue

            question = item.get("question", "N/A")
            answer = item.get("answer", "N/A")
            score = item.get("score", "N/A")
            feedback = item.get("feedback", "N/A")

            # Page break
            if y < 140:
                c.showPage()
                y = height - 60

            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, f"Q{i}: {question[:80]}")
            y -= 18

            c.setFont("Helvetica", 11)
            c.drawString(60, y, f"Score: {score}/10")
            y -= 16

            y = add_text_block("Feedback:", feedback, y, font_size=10)
            y = add_text_block("Candidate Answer:", answer, y, font_size=10)

            y -= 10
            c.line(50, y, width - 50, y)
            y -= 20

    else:
        c.setFont("Helvetica", 11)
        c.drawString(50, y, "No question-wise evaluation available.")
        y -= 20

    # ---------------- FOOTER ----------------
    if y < 80:
        c.showPage()

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 40, "Generated by AI Interview Bot (MAANG Style)")

    # ---------------- SAVE PDF ----------------
    c.save()
    buffer.seek(0)

    return buffer.getvalue()
